### ISSUE TITLE
Bot API 2.0

### ISSUE THREAD

**Issue by AnatolyRugalev** [mukel/telegrambot4s#10]
Thank you for great library, I'm  beginner in Scala, but everything looks very easy to use for me.

Recently Telegram announced [Bot API 2.0](https://core.telegram.org/bots/2-0-intro). Do you have any plans to implement new features like inline keyboards, location and phone number sharing?

**Comment by mukel** [comment]
Yes, I've been planning a huge refactoring and now looks like a good time. I cannot say exactly when but the version 2 of the library is near.

**Comment by mukel** [comment]
Updated on May 6th, inline goodies are fully supported
