### ISSUE TITLE
Error code in TelegramApiException

### ISSUE THREAD

**Issue by pkalatski** [mukel/telegrambot4s#13]
Would be nice to have a telegram error code available in exception. I.e. in case of 429 ([Error]: Too many requests: retry later) API user might want to resend the message with some delay instead of failing.

**Comment by mukel** [comment]
Thanks!, now the exception includes the error code. I'll update the README soon with instructions on how to add the latest snapshot as a dependency.

**Comment by mukel** [comment]
Updated README, please try the latest (fixed) SNAPSHOT, feedback is greatly appreciated.

**Comment by pkalatski** [comment]
Thanks a lot! Updated to latest snapshot and error code is there.
