### ISSUE TITLE
Incorrect order of messages when polling is used

### ISSUE THREAD

**Issue by nzhiltsov** [mukel/telegrambot4s#16]
There is an incorrect order of messages (sent by api.request(SendMessage)), when the polling method is used. How to keep sent messages in order? Is there any way to fix that without using webhooks?

**Comment by mukel** [comment]
Yes that's the expected behavior, but I see your point, basically you want to enforce a sequential order of requests (maybe for some special part, but not necessarily for everything), could you give me more details? how it breaks? and what is exactly your use case?

**Comment by mukel** [comment]
Fixed
