### ISSUE TITLE
Verbose loge messages to console by default

### ISSUE THREAD

**Issue by eliseealex** [mukel/telegrambot4s#18]
Printing to console all http messages by default leads to verbose output: https://github.com/mukel/telegrambot4s/blob/e1d6c9938d43d1daef5e1f16460f37da5c7a6372/src/main/scala/info/mukel/telegrambot4s/api/TelegramApiAkka.scala#L59.

In many case i would like to ignore this messages, but i can't. Please, use logging instead of printing to console. For example, using https://github.com/typesafehub/scala-logging. It will help users to control library output.

**Comment by mukel** [comment]
My bad, I left some println dirt, I started to add basic logging. [](https://github.com/mukel/telegrambot4s/blob/master/src/main/scala/info/mukel/telegrambot4s/api/TelegramBot.scala#L21)
, but didn't quite finished, I'll do some cleanup, but I know just the basic about logging. In the meantime if you have a better way that fullfill real use cases please feel free to submit a PR, it will be really appreciated.

**Comment by onilton** [comment]
I think I solved the println issue in #19 . But did not work in logging yet :stuck_out_tongue:
