### ISSUE TITLE
release to sonatype?

### ISSUE THREAD

**Issue by larroy** [mukel/telegrambot4s#22]
Any interest in releasing to sonatype? I can help with that..

**Comment by mukel** [comment]
I use to have Sonatype snapshot releases at the very beginning, but Jitpack is just more convenient for me. I don't have to even publish anything, Jitpack pulls, builds... on users demand.
I'd be happy to include Sonatype releases if the publishing process is simple on my side. Any hint?

**Comment by larroy** [comment]
I can publish for you, but I could only host the artifact in a different org. I have never used jitpack before. I will have a look to understand what it is.

**Comment by mukel** [comment]
I found your Sonatype tutorial, I'll start testing the Sonatype releases for Scala 2.12 and 2.11 soon.

**Comment by mukel** [comment]
Done, including 2.12 release, will release soon.

**Comment by larroy** [comment]
👌
