### ISSUE TITLE
Actor bindings architecture

### ISSUE THREAD

**Issue by mukel** [mukel/telegrambot4s#25]
The actor bindings open new ways of building bots; FSM actors will greatly simplify the creation of stateful workflows leveraging over a widely known and used model (FSM Actors).

Actor bindings can be added by mixing [ActorDispatcher](https://github.com/mukel/telegrambot4s/blob/master/src/main/scala/info/mukel/telegrambot4s/actors/ActorDispatcher.scala).

Here's an example of a very simple per-chat dispatcher:
[Per-chat actor dispatcher](https://gist.github.com/mukel/40b06e97069ab08bdecf3ba9df8776d5)

The purpose of this issue is to agree on a general design for a more powerful abstraction.
Possibly including:
  - FSM
  - Expiring actors
  - State management and persistency

**Comment by mukel** [comment]
@zifeo PTAL

**Comment by zifeo** [comment]
Looks good! A few ideas/comments unordered:
- might the name `dispatcher` be confused with the system dispatcher?
- should be clear whether the availability of other commands changes when a worker is active for a given channel?
- would the broker example be included in the lib?
