### ISSUE TITLE
Self signed certificate valid :)

### ISSUE THREAD

**Issue by rockneurotiko** [mukel/telegrambot4s#3]
With the last change the added support to self-signed certificates ;-)

[changes](https://core.telegram.org/bots/api#recent-changes)

**Comment by mukel** [comment]
I already updated the API, but haven't tested the self-signed certificates yet, I'll test it and update the README soon, thanks

**Comment by mukel** [comment]
Webhooks works on the new cersion

**Comment by mukel** [comment]
But the self signed certificates must be issued by hand
