### ISSUE TITLE
Commands hijacking for bots with access to messages

### ISSUE THREAD

**Issue by kejran** [mukel/telegrambot4s#37]
Bot name after the `@` is not checked. If a bot has been granted full access to messages in a chat, it will inspect all commands and execute their callbacks while ignoring which bot the command was actually adressed to. 

for example, typing `/start@youtube` while my bot is present with access to messages will execute the `/start` command on my bot.

**Comment by mukel** [comment]
All my bots run on privacy mode, but indeed, keep tuned I'll push a fix soon.

**Comment by mukel** [comment]
Fixed on v3.0.8, it now respect receiver suffix (case-insensitive). Thanks for reporting.
Configurable overriding `ignoreCommandReceiver` (false by default).
