### ISSUE TITLE
SocketTimeoutException in TelegramBot.getUpdates()

### ISSUE THREAD

**Issue by nzhiltsov** [mukel/telegrambot4s#4]
There is a SocketTimeoutException when the bot does not receive any messages from the user. How to handle long polling properly? Increase timeout or switch to using webhooks?

**Comment by mukel** [comment]
Thanks, I'll take a look this weekend. Polling is still the simpler method but Telegram removed the certificate limitation and now it's easier to set a webhook, you can take a look to https://github.com/mukel/GenginedBot for Google App Engine bot. I'll give some maintenance as soon as I have some free time.

**Comment by mukel** [comment]
Updated a few things, but I can't reproduce the problem, it must be related to ScalajHttp timeouts, I doubled the timeouts as a temporal hack, but the timeout exception should be wrapped on the Future anyways.

**Comment by nzhiltsov** [comment]
Thanks for the quick reply. Will try it.

**Comment by mukel** [comment]
Timeouts should be solved in the new version
