### ISSUE TITLE
Custom command prefix 

### ISSUE THREAD

**Issue by NKozlov** [mukel/telegrambot4s#41]
I need to start command without prefix "/". Add possibility to api change ```CommandPrefix```.

**Comment by mukel** [comment]
The default prefix gives auto-completion, but you must declare the commands statically with BotFather.
Do you need to support several prefixes, or just change the default prefix?
For the record, Could you provide more detailed information about your use case?

**Comment by NKozlov** [comment]
Thanks for your reply. I think i want support several prefixes.
In my case i have keyboard with two buttons "Office" and "Metro". When user push the "Office" button, telegram-client send text to bot "Office" and in your implementation of commands, bot not understand this command. I want have user-friendly buttons.
You can see it on my github: https://github.com/NKozlov/lanit-bus-bot/blob/master/src/main/scala/pro/nkozlov/telegram/bots/lanitbus/LanitBusBot.scala

**Comment by mukel** [comment]
The Commands interface is designed to support Telegram commands. Other libraries support different command prefixes but no prefix-less commands.

Prefix-less commands have a few disadvantages, e.g. if user types "Office" or "Metro" out of context, getting unexpected responses.
Prefix-less commands would make sense in an stateful workflow (e.g. BotFather) where the bot expect answers depending on the current state. This can be achieved using FSM actors.

Another way would be to use Inline buttons, which are part of a message (not a special keyboard). 
Is possible to trigger commands from inline buttons. Since it's possible to edit messages, you can create interactive interfaces (try command /beers in [EpflBot](https://t.me/EpflBot) for an example).

Your solution is perfectly fine for your use case and I'm glad you could extend the library to fit your needs.

**Comment by NKozlov** [comment]
Don't close issue please =) 
Thanks for your reply and suggestions about resolve of my case.
As i understand you right, in your client impossible create bot keyboard with user-friendly names? This is very strange, don't? I only ask to be given the opportunity to change default command prefix, if i want (one way is extend of class, another way is providing client-api).

Ok if i won't create inline buttons, i can extend your api and added my realisation. But in version 3.0.9 you change scope of method to `private[telegrambot4s]` and my code don't work with new version of client.

**Comment by mukel** [comment]
KeyboardButton allows to send custom keyboards but with the limitation that clicking the button is equivalent to write the button label/text as a message, this is a limitation of the Telegram API not the library. These buttons are more like a shortcut for canned predefined responses. e.g. Yes, No, 👍 👎, 1 to 5 star rating selection.

To create buttons with user-friendly labels use inline buttons which are more flexible, including callbacks (e.g. onClick handler). I've seen Sudokus and Tic-Tac-Toe games are implemented using inline buttons + EditMessage.

My point is that your use case is rather specific and can be achieved by implementing your own handler (maybe is not uber clean, but is doable). I would consider to support more prefixes (eg. % and #) alongside "/" but refuse to go prefix-less.

This is my attempt for your use case:
```scala
class TextBot(token: String) extends ExampleBot(token) with Polling with Commands {

  // Prefix-less commands.
  def onTextCommand(textCommand: String)(action: Action[Message]): Unit = {
    onMessage { implicit msg =>
      using(textTokens) {
        case Seq(cmd) if textCommand.equalsIgnoreCase(cmd) => action(msg)
        case _ =>
      }
    }
  }

  // Regular /command + prefix-less variant.
  def onTextCommand[T: ToCommand](command: T, textCommand: String)(action: Action[Message]): Unit = {
    onCommand(command)(action)
    onTextCommand(textCommand)(action)
  }

  // Common handler.
  def helloHandler(msg: Message): Unit = {
    reply("Hello World!")(msg)
  }

  // Separate.
  onTextCommand("Hello")(helloHandler)
  onCommand('hello)(helloHandler)

  // Combined.
  onTextCommand('beer, "Beer") {
    implicit msg =>
      reply("Beer!")
  }
}
```

**Comment by NKozlov** [comment]
thanks, man, for your opinion. 
I know, that this is a limitation of the Telegram API not the library, i just talk about possibility of changing this behavior at the library level. 
You suggest me the way to realise this feature in my project. It one of the way and i have it. Thank you for the proposed implementation. U can close issue, thanks man!
