### ISSUE TITLE
Is there a way for a bot to start voice recording?

### ISSUE THREAD

**Issue by ferrlin** [mukel/telegrambot4s#47]
I am using deep link to start telegram mobile app. I want to add a command to the bot and one of this is to start voice recording when chat app opens.

Is this possible with telegrambot4s?

Thanks,

**Comment by mukel** [comment]
This is not possible AFAIK, this is a limitation of the Telegram API, not of the library. The user must initiate the recording, all you can do is show a message leading the user to send a recording.

**Comment by ferrlin** [comment]
thanks for the reply.
