### ISSUE TITLE
The command receiver check should be done comparing the bot username, not its first name.

### ISSUE THREAD

**Issue by devcexx** [mukel/telegrambot4s#53]
Currently, when a message is received and the receiver is extracted from the received text, it is compared against the first name of the bot instead of comparing it with its username, as the Telegram client suggests while typing a command like [here](https://prnt.sc/ie7hij).

This is because, in `info.mukel.telegrambot4s.api.declarative.Commands`, the field `botName` holds the first name of the bot instead of its username.

**Comment by devcexx** [comment]
I'm creating the PR #54 as a possible solution of the issue.

**Comment by mukel** [comment]
Closed in #54
