### ISSUE TITLE
How to stop the running bot?

### ISSUE THREAD

**Issue by rafis** [mukel/telegrambot4s#55]
I start `sbt` and then `run` my bot. How do I stop it? And another small question. I was using `~run` with tilda at the beginning of the command, it means something like watch mode I think and it this working (when I change source code sbt detects it and was recomplining automatically) but now doesn't.

**Comment by mukel** [comment]
There's a `.shutdown()` method which returns a Future[Unit]. It's completed after some cleanup.
My usual workflow is just `sbt ~compile`, depending on the bot, restarting can be expensive. What's exactly the problem, SBT doesn't re-compile? or the bot re-starts throwing exceptions?

**Comment by rafis** [comment]
Thank you, it seems works:

```scala
    SafeBot.run()
    scala.io.StdIn.readLine()
    SafeBot.shutdown()
```
