### ISSUE TITLE
Unable to connect: "Failed to clear webhook"|"Connection reset by peer"

### ISSUE THREAD

**Issue by Tieru** [mukel/telegrambot4s#61]
Hello, my bot is failing to start with error

```
Failed to clear webhook
akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
```

My guess is my connection to Telegram servers gets blocked. 

Among your resent issues I saw your answer about proxy support. Is it still possible to access your refactored version (3.1.0-RC1)?

**Comment by mukel** [comment]
It could be that you have another instance of your bot already running e.g. in the background, an instance that didn't died even if you Ctrl-C it... it happens.
Make sure to run a single instance of your bot. Kill all the java processes.

**Comment by Tieru** [comment]
You are probably right, but I've just tried running another bot which has never been launched before. The error reminds the same. So I still think, proxy will help me :)

**Comment by mukel** [comment]
You can pull the proxy logic yourself.
Just need to copy [ScalajHttpClient.scala](https://github.com/mukel/telegrambot4s/blob/refactor/core/src/info/mukel/telegrambot4s/clients/ScalajHttpClient.scala) and [ScalajHttpMarshalling](https://github.com/mukel/telegrambot4s/blob/refactor/core/src/info/mukel/telegrambot4s/marshalling/ScalajHttpMarshalling.scala) and use it as you client.
Here's an example 
https://github.com/mukel/telegrambot4s/blob/refactor/examples/src/ProxyBot.scala

**Comment by Tieru** [comment]
I tried to copy two mentioned files, but no luck. These classes depend on changes in **JsonMarshallers**, **RequestHandler**, which I managed to repeat in my project as well. But there is one more thing I can't solve: **ScalajHttpMarshalling** is working with [**sealed trait InputFile**](https://github.com/mukel/telegrambot4s/blob/refactor/core/src/info/mukel/telegrambot4s/models/InputFile.scala), and I can't apply [_**case**_](https://github.com/mukel/telegrambot4s/blob/6d3e6e500711d98a8c6481fbb672e06b4238a788/core/src/info/mukel/telegrambot4s/marshalling/ScalajHttpMarshalling.scala#L37) operator on project private classes **Path**, **Contents** etc

**Comment by mukel** [comment]
I'm on vacation ATM (no laptop) but I could publish an RC2 with the recent patches and proxy support next week.
I've been working on a large refactor (ScalaJs support, circe-based serialization, proxy support via ScalajHttpClient, modular design...) You can try building from source the [js](https://github.com/mukel/telegrambot4s/tree/js?files=1) branch (it uses mill instead of SBT).
Sorry for the inconvenience, feel free to open an issue or continue the discussion here, I'll galdly help you sort it out.

**Comment by Tieru** [comment]
I can wait, I don't have urgent tasks :) 

Btw, here is the bot I created using your library (just a dictionary of English words): https://github.com/Tieru/MacMillanTelegramBot . If you have time to look at that, any feedback is welcome.

I can also help you with maintaining your library. When you are back from your vacation you can delegate me simple tasks that you have in mind, but have no time to spend on them.

Please let this issue open until we try proxy. I guess many Russians will have problems with running their bots, so this topics might be a solution for them in the future.

**Comment by Tieru** [comment]
I couldn't find any proxy support in 'js' branch. However I tried 'refactor' and now I can confirm that proxy does solve the issue! Thanks for your help!

**Comment by Tieru** [comment]
Hello, @mukel . Could you please release a version that includes proxy? I have built a jar that includes those changes and it's fine for development, but deploy process to server or to another pc is a bit painful. 

Probably I could help you somehow in order to save your time and prepare new releases

**Comment by mukel** [comment]
Closing this in favor of #63
